default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vote_me_dev

test:
  <<: *default
  database: vote_me_test

production:
  <<: *default
  database: vote_me_production
